services:
  ollama:
    image: ollama/ollama:0.20.3
    container_name: ollama_test
    # pull de la imagen que quiero "tinyllama"
    ports: 
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
  api:
    build: ./api
    container_name: fastapi_llm
    ports:
      - "8001:8000"
    environment:
    - INFERENCE_URL=http://ollama:11434
    depends_on:
      - ollama

volumes:
  ollama_data: